server:
  port: 8084
spring:
  rabbitmq:
    host: ${MQ_HOST:localhost}
    port: ${MQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:admin}
    password: ${RABBITMQ_DEFAULT_PASS:password}
  datasource:
    url: ${DB_ADDRESS:jdbc:postgresql://localhost:5432/telegram}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
config:
  bot:
    name:
    token:
  service:
    file_storage:
      uri: https://api.telegram.org/bot{token}/getFile?file_id={fileId}
    file_info:
      uri: https://api.telegram.org/file/bot{token}/{filePath}
